#! /bin/bash

PACK=false

while getopts p OPT
  do 
    case $OPT in
    p)  PACK=true;;
    \?) usage_exit;;
    esac
  done

shift $(( OPTIND - 1 ))

INPUT=$([ -p /dev/stdin ] && cat || cat "$1")

cd "$HOME/WINHOME/Desktop/"
DEST=$(date +%Y%m%d_%H%M%S) 
mkdir "$DEST"

if $PACK ; then cd "$DEST"; fi

echo "$INPUT" | xargs -d '\n' -I% cp -r % .

if $PACK ; then :; else rm -r "$DEST"; fi
